spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: spring-boot
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:spring_boot}?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER:spring_boot}
    password: ${MYSQL_PASSWORD:spring_boot}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
